### ISSUE TITLE
Error 'unimplemented hole' not visible in web interface

### ISSUE THREAD

**Issue by isberg** [exercism/idris-test-runner#12]
When having an unimplemented hole in the source file it will show up locally when running the tests, but in the web interface it will just say tests failed. This is likely due to the [sanitization of the test feedback](https://github.com/exercism/idris-test-runner/blob/2d9735e795fa0fae49b279e54f0c1f6f6cbd586d/bin/run.sh#L55) being a bit aggressive, or, more likely, primitive: `head --lines=-4 -`

**Comment by keiravillekode** [comment]
Should we eliminate that sanitization? Idris2 might have better error reporting than Idris1.

**Comment by isberg** [comment]
I think it should be done similar to [the one above](https://github.com/exercism/idris-test-runner/blob/2d9735e795fa0fae49b279e54f0c1f6f6cbd586d/bin/run.sh#L37), because otherwise it is probably to noisy.
